version: '3.9'
services:
  mysql.dev.db:
    container_name: mysql.dev.db
    ports:
      - 4406:3306
    platform: linux/x86_64
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-dev-data:/var/lib/mysql
    networks:
      - dev-net
volumes:
  mysql-dev-data:
networks:
  dev-net:
    driver: bridge
    name: dev-net
